server:
  address: 0.0.0.0
  port: 8085

spring:
  application:
    name: bug-vision
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        generate_statistics: true
        jdbc:
          batch_size: 4
          lob.non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE-USERNAME:postgres}
    password: ${DATASOURCE-PASSWORD:postgres}
    url: ${DATASOURCE-URL:jdbc:postgresql://localhost:5432/bug_vision}
    tomcat:
      initial-size: 10
      max-active: 20
      max-wait: 10000

bug-vision:
  core: ${BUG-VISION-CORE-URL:http://localhost:5000}

db:
  preset: ${DB-PRESET:basic}

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug

app:
  properties:
    jwtSecret: yubeSecretKey
    jwtExpirationMs: 86400000